### ISSUE TITLE
Installation on Windows does not work

### ISSUE THREAD

**Issue by sariths** [taoning/pyenergyplus#1]
The installation using pip install zipFileUrl only saves the dist-info directory to the instlalled libraries folder.

![image](https://github.com/taoning/pyenergyplus/assets/10361848/46863c3c-dcc4-4fb3-9eea-952f352e6371)

**Comment by taoning** [comment]
Trying to have pip auto select wheel through a zip url turns out to be tricky.  Now all wheels are included directly in release. Users have to select the right wheel to install before we move to pypi.
